# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af35a591ffb9a6189b23214bd5a029cedec6e3261cab95074eb1ede5d6e3027e13523055af8031eebfafa5c38d80d39f544e1f16fe15b648996fd683ac6fed8

test:
  secret_key_base: 185f07bb19446edaadf662727c9c34aabd718e23218631ca975c6862014053ef204c5bf55041064781fa13450d907b264a5e8bcac7f10bcfeb9d8111d4b18450

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
